"""Map stable domain identifiers to translation keys, never to stored labels."""

from localization import tr


STRATAGEM_LABELS = {'Orbital Precision Strike': 'stratagems.orbital_precision_strike',
 'Orbital Gatling Barrage': 'stratagems.orbital_gatling_barrage',
 'Orbital Gas Strike': 'stratagems.orbital_gas_strike',
 'Orbital 120mm HE Barrage': 'stratagems.orbital_120mm_he_barrage',
 'Orbital Airburst Strike': 'stratagems.orbital_airburst_strike',
 'Orbital Smoke Strike': 'stratagems.orbital_smoke_strike',
 'Orbital EMS Strike': 'stratagems.orbital_ems_strike',
 'Orbital 380mm HE Barrage': 'stratagems.orbital_380mm_he_barrage',
 'Orbital Walking Barrage': 'stratagems.orbital_walking_barrage',
 'Orbital Laser': 'stratagems.orbital_laser',
 'Orbital Napalm Barrage': 'stratagems.orbital_napalm_barrage',
 'Orbital Railcannon Strike': 'stratagems.orbital_railcannon_strike',
 'Eagle Gas Airstrike': 'stratagems.eagle_gas_airstrike',
 'Eagle Strafing Run': 'stratagems.eagle_strafing_run',
 'Eagle Airstrike': 'stratagems.eagle_airstrike',
 'Eagle Cluster Bomb': 'stratagems.eagle_cluster_bomb',
 'Eagle Smoke Strike': 'stratagems.eagle_smoke_strike',
 'Eagle Napalm Airstrike': 'stratagems.eagle_napalm_airstrike',
 'Eagle 110mm Rocket Pods': 'stratagems.eagle_110mm_rocket_pods',
 'Eagle 500kg Bomb': 'stratagems.eagle_500kg_bomb',
 'MG-43 Machine Gun': 'stratagems.mg_43_machine_gun',
 'EAT-17 Expendable Anti-Tank': 'stratagems.eat_17_expendable_anti_tank',
 'M-105 Stalwart': 'stratagems.m_105_stalwart',
 'LAS-98 Laser Cannon': 'stratagems.las_98_laser_cannon',
 'APW-1 Anti-Materiel Rifle': 'stratagems.apw_1_anti_materiel_rifle',
 'GR-8 Recoilless Rifle': 'stratagems.gr_8_recoilless_rifle',
 'GL-21 Grenade Launcher': 'stratagems.gl_21_grenade_launcher',
 'FLAM-40 Flamethrower': 'stratagems.flam_40_flamethrower',
 'MG-206 Heavy Machine Gun': 'stratagems.mg_206_heavy_machine_gun',
 'AC-8 Autocannon': 'stratagems.ac_8_autocannon',
 'ARC-3 Arc Thrower': 'stratagems.arc_3_arc_thrower',
 'LAS-99 Quasar Cannon': 'stratagems.las_99_quasar_cannon',
 'RL-77 Airburst Rocket Launcher': 'stratagems.rl_77_airburst_rocket_launcher',
 'MLS-4X Commando': 'stratagems.mls_4x_commando',
 'FAF-14 Spear': 'stratagems.faf_14_spear',
 'RS-422 Railgun': 'stratagems.rs_422_railgun',
 'StA-X3 W.A.S.P. Launcher': 'stratagems.sta_x3_w_a_s_p_launcher',
 'CQC-20 Breaching Hammer': 'stratagems.cqc_20_breaching_hammer',
 'PLAS-45 Epoch': 'stratagems.plas_45_epoch',
 'MGX-42 Bullet Storm': 'stratagems.mgx_42_bullet_storm',
 'S-11 Speargun': 'stratagems.s_11_speargun',
 'CQC-9 Defoliation Tool': 'stratagems.cqc_9_defoliation_tool',
 'GL-52 De-Escalator': 'stratagems.gl_52_de_escalator',
 'EAT-700 Expendable Napalm': 'stratagems.eat_700_expendable_napalm',
 'TX-41 Sterilizer': 'stratagems.tx_41_sterilizer',
 'EAT-411 Leveller': 'stratagems.eat_411_leveller',
 'GL-28 Belt-Fed Grenade Launcher': 'stratagems.gl_28_belt_fed_grenade_launcher',
 'B/MD C4 Pack': 'stratagems.b_md_c4_pack',
 'MS-11 Solo Silo': 'stratagems.ms_11_solo_silo',
 'B/FLAM-80 Cremator': 'stratagems.b_flam_80_cremator',
 'M-1000 Maxigun': 'stratagems.m_1000_maxigun',
 'CQC-1 One True Flag': 'stratagems.cqc_1_one_true_flag',
 '40-K Meltagun': 'stratagems.40_k_meltagun',
 'B-1 Supply Pack': 'stratagems.b_1_supply_pack',
 'LIFT-850 Jump Pack': 'stratagems.lift_850_jump_pack',
 'SH-20 Ballistic Shield Backpack': 'stratagems.sh_20_ballistic_shield_backpack',
 'AX/AR-23 Guard Dog': 'stratagems.ax_ar_23_guard_dog',
 'AX/LAS-5 Rover': 'stratagems.ax_las_5_rover',
 'SH-32 Shield Generator Pack': 'stratagems.sh_32_shield_generator_pack',
 'SH-51 Directional Shield': 'stratagems.sh_51_directional_shield',
 'AX/FLAM-75 Hot Dog': 'stratagems.ax_flam_75_hot_dog',
 'B-100 Portable Hellbomb': 'stratagems.b_100_portable_hellbomb',
 'AX/ARC-3 K-9': 'stratagems.ax_arc_3_k_9',
 'LIFT-860 Hover Pack': 'stratagems.lift_860_hover_pack',
 'AX/TX-13 Dog Breath': 'stratagems.ax_tx_13_dog_breath',
 'LIFT-182 Warp Pack': 'stratagems.lift_182_warp_pack',
 'M-103 Supply FRV': 'stratagems.m_103_supply_frv',
 'M-104 Incinerator FRV': 'stratagems.m_104_incinerator_frv',
 'EXO-49 Emancipator Exosuit': 'stratagems.exo_49_emancipator_exosuit',
 'EXO-45 Patriot Exosuit': 'stratagems.exo_45_patriot_exosuit',
 'M-102 Gunner FRV': 'stratagems.m_102_gunner_frv',
 'TD-220 Bastion MK XVI': 'stratagems.td_220_bastion_mk_xvi',
 'EXO-55 Breakthrough Exosuit': 'stratagems.exo_55_breakthrough_exosuit',
 'EXO-51 Lumberer Exosuit': 'stratagems.exo_51_lumberer_exosuit',
 'A/MG-43 Machine Gun Sentry': 'stratagems.a_mg_43_machine_gun_sentry',
 'A/G-16 Gatling Sentry': 'stratagems.a_g_16_gatling_sentry',
 'A/AC-8 Autocannon Sentry': 'stratagems.a_ac_8_autocannon_sentry',
 'A/M-12 Mortar Sentry': 'stratagems.a_m_12_mortar_sentry',
 'A/MLS-4X Rocket Sentry': 'stratagems.a_mls_4x_rocket_sentry',
 'A/ARC-3 Tesla Tower': 'stratagems.a_arc_3_tesla_tower',
 'A/M-23 EMS Mortar Sentry': 'stratagems.a_m_23_ems_mortar_sentry',
 'A/LAS-98 Laser Sentry': 'stratagems.a_las_98_laser_sentry',
 'A/FLAM-40 Flame Sentry': 'stratagems.a_flam_40_flame_sentry',
 'A/GM-17 Gas Mortar Sentry': 'stratagems.a_gm_17_gas_mortar_sentry',
 'MD-6 Anti-Personnel Minefield': 'stratagems.md_6_anti_personnel_minefield',
 'MD-I4 Incendiary Mines': 'stratagems.md_i4_incendiary_mines',
 'MD-17 Anti-Tank Mines': 'stratagems.md_17_anti_tank_mines',
 'FX-12 Shield Generator Relay': 'stratagems.fx_12_shield_generator_relay',
 'E/MG-101 HMG Emplacement': 'stratagems.e_mg_101_hmg_emplacement',
 'E/GL-21 Grenadier Battlement': 'stratagems.e_gl_21_grenadier_battlement',
 'MD-8 Gas Mines': 'stratagems.md_8_gas_mines',
 'E/AT-12 Anti-Tank Emplacement': 'stratagems.e_at_12_anti_tank_emplacement',
 'Eagle Rearm': 'stratagems.eagle_rearm',
 'Call In Super Destroyer': 'stratagems.call_in_super_destroyer',
 'Reinforce': 'stratagems.reinforce',
 'SoS Beacon': 'stratagems.sos_beacon',
 'Resupply': 'stratagems.resupply',
 'Cargo Container': 'stratagems.cargo_container',
 'NUX-223 Hellbomb': 'stratagems.nux_223_hellbomb',
 'Seismic Probe': 'stratagems.seismic_probe',
 'SSSD Delivery': 'stratagems.sssd_delivery',
 'Tectonic Drill': 'stratagems.tectonic_drill',
 'Upload Data': 'stratagems.upload_data',
 'Reinforcement Pods': 'stratagems.reinforcement_pods',
 'Tactical Video Camera': 'stratagems.tactical_video_camera',
 'Aquifer Drill': 'stratagems.aquifer_drill',
 'Portable Comms Relay': 'stratagems.portable_comms_relay',
 'Prospecting Drill': 'stratagems.prospecting_drill',
 'Hive Breaker Drill': 'stratagems.hive_breaker_drill',
 'Activate E-711 Extraction Drill': 'stratagems.activate_e_711_extraction_drill',
 'Dark Fluid Vessel': 'stratagems.dark_fluid_vessel',
 'Super Earth Flag': 'stratagems.super_earth_flag',
 'SEAF Artillery': 'stratagems.seaf_artillery',
 'Orbital Illumination Flare': 'stratagems.orbital_illumination_flare'}

CATEGORY_LABELS = {'Offensive Permit': 'categories.offensive_permit',
 'Orbital Strikes': 'categories.orbital_strikes',
 'Eagle Strikes': 'categories.eagle_strikes',
 'Supply Permit': 'categories.supply_permit',
 'Support Weapons': 'categories.support_weapons',
 'Backpacks': 'categories.backpacks',
 'Vehicles': 'categories.vehicles',
 'Defensive Permit': 'categories.defensive_permit',
 'Sentries': 'categories.sentries',
 'Emplacements': 'categories.emplacements',
 'Other': 'categories.other',
 'Mission Stratagems / Ship': 'categories.mission_stratagems_ship',
 'Mission Stratagems / Objective': 'categories.mission_stratagems_objective',
 'Mission Stratagems / Unavailable': 'categories.mission_stratagems_unavailable'}

MODIFIER_LABELS = {'orbital_fluctuations': 'modifiers.orbital_fluctuations',
 'streamlined_request_process': 'modifiers.streamlined_request_process',
 'hand_carts': 'modifiers.hand_carts',
 'zero_g_breech_loading': 'modifiers.zero_g_breech_loading',
 'liquid_ventilated_cockpit': 'modifiers.liquid_ventilated_cockpit',
 'morale_augmentation': 'modifiers.morale_augmentation',
 'synthetic_supplementation': 'modifiers.synthetic_supplementation'}


def stratagem_label(identifier):
    key = STRATAGEM_LABELS.get(identifier)
    return tr(key) if key else identifier


def category_label(identifier):
    key = CATEGORY_LABELS.get(identifier)
    return tr(key) if key else identifier


def modifier_label(identifier):
    key = MODIFIER_LABELS[identifier]
    return tr(key + ".name") + "\n" + tr(key + ".description")
